#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the #first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even
#-valued terms.

x  <- c(1,2)
length(x)
i  <- 1
while(x[i] < 4000000){
  i <- i+1
  x.index  <- length(x)
  x[x.index + 1]  <- x[x.index] + x[x.index - 1]
}
sum(x[x%%2 == 0])



#If  you know that there are 33 numbers in the sequence
len  <- 33
fibo  <- numeric(10)
fibo[1]  <- 1
fibo[2]  <- 1

for(i in 3:len){
  fibo[i]  <- fibo[i-1] + fibo[i-2]
}

sum(fibo[!(fibo[fibo<4000000])%%2])
